export const API_URL = 'http://localhost:8080'
export const API_URL_USERS = 'http://localhost:8080/users'
export const API_URL_UPDATE_USER = 'http://localhost:8080/users/update'
export const API_URL_USER_DELETE = 'http://localhost:8080/users/delete'
export const API_URL_EXPENSES = 'http://localhost:8080/expenses'
export const API_URL_EXPENSE_DELETE = 'http://localhost:8080/expenses/delete'
export const API_URL_UPDATE_EXPENSE = 'http://localhost:8080/expenses/update'